export const BOOK_TAGS = [
  "Dark Academia",
  "Found Family",
  "Slow Burn",
  "Dystopian",
  "Fantasy",
  "Science Fiction",
  "Romance",
  "Queer Literature",
  "Feminist Literature",
  "Postcolonial",
  "Psychological",
  "Horror",
  "Mystery",
  "Thriller",
  "Literary Fiction",
  "Cozy",
  "Political",
  "Classic",
  "Young Adult",
  "Historical Fiction",
];